/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        app: {
          bg: '#0a0c0f',
          card: '#13171f',
          'card-hover': '#1c222e',
          border: '#2b3345',
          text: '#f0f3f8',
          muted: '#8a96a8',
        },
        team: {
          primary: 'var(--team-primary, #007A33)',
          secondary: 'var(--team-secondary, #BA9653)',
          contrast: 'var(--team-contrast, #FFFFFF)',
          glow: 'var(--team-glow, rgba(0, 122, 51, 0.25))',
        },
        // Stitch Hoop Legacy Design System Tokens
        "on-error-container": "#ffdad6",
        "surface-tint": "#29e465",
        "surface-container": "#1c2025",
        "secondary": "#77dc88",
        "primary-container": "#00d659",
        "secondary-container": "#007932",
        "on-primary": "#003912",
        "surface-dim": "#101419",
        "inverse-primary": "#006e2a",
        "surface-container-low": "#181c21",
        "on-secondary-container": "#99fea7",
        "on-secondary-fixed-variant": "#005320",
        "on-surface-variant": "#bbcbb7",
        "tertiary": "#ffce76",
        "on-background": "#e0e2ea",
        "outline-variant": "#3c4a3b",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#fbbc38",
        "primary-fixed": "#6aff87",
        "surface-bright": "#36393f",
        "primary": "#42f372",
        "surface-container-high": "#262a30",
        "tertiary-fixed": "#ffdea8",
        "error-container": "#93000a",
        "secondary-fixed": "#93f9a2",
        "surface": "#101419",
        "tertiary-container": "#edaf2b",
        "on-surface": "#e0e2ea",
        "on-primary-container": "#00561f",
        "inverse-on-surface": "#2d3136",
        "outline": "#859583",
        "surface-container-lowest": "#0a0e13",
        "on-primary-fixed-variant": "#00531e",
        "surface-container-highest": "#31353b",
        "primary-fixed-dim": "#29e465",
        "on-tertiary-fixed": "#271900",
        "on-tertiary": "#422d00",
        "inverse-surface": "#e0e2ea",
        "background": "#101419",
        "on-error": "#690005",
        "surface-variant": "#31353b",
        "secondary-fixed-dim": "#77dc88",
        "on-primary-fixed": "#002108",
        "on-tertiary-fixed-variant": "#5e4200",
        "on-tertiary-container": "#624400",
        "on-secondary": "#003914",
        "on-secondary-fixed": "#002109"
      },
      spacing: {
        "margin-desktop": "2rem",
        "gutter-desktop": "1rem",
        "space-sm": "0.5rem",
        "gutter": "0.75rem",
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "margin": "1rem"
      },
      fontFamily: {
        condensed: ['"Barlow Condensed"', 'Oswald', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'Roboto Mono', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        "body-md": ["Chivo", "sans-serif"],
        "body-lg": ["Chivo", "sans-serif"],
        "headline-xl-mobile": ['"Barlow Condensed"', "sans-serif"],
        "headline-xl": ['"Barlow Condensed"', "sans-serif"],
        "headline-lg": ['"Barlow Condensed"', "sans-serif"],
        "stat-mono-md": ['"JetBrains Mono"', "monospace"],
        "label-caps": ['"Barlow Condensed"', "sans-serif"],
        "headline-md": ['"Barlow Condensed"', "sans-serif"],
        "display-hero": ['"Barlow Condensed"', "sans-serif"],
        "display-hero-mobile": ['"Barlow Condensed"', "sans-serif"],
        "headline-sm": ['"Barlow Condensed"', "sans-serif"],
        "stat-mono-sm": ['"JetBrains Mono"', "monospace"],
        "body-sm": ["Chivo", "sans-serif"],
        "stat-display": ['"JetBrains Mono"', "monospace"]
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl-mobile": ["28px", { lineHeight: "32px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "44px", letterSpacing: "0.01em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "700" }],
        "stat-mono-md": ["14px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps": ["13px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "26px", letterSpacing: "0.03em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "60px", letterSpacing: "0.02em", fontWeight: "800" }],
        "display-hero-mobile": ["38px", { lineHeight: "42px", letterSpacing: "0.02em", fontWeight: "800" }],
        "headline-sm": ["18px", { lineHeight: "22px", letterSpacing: "0.04em", fontWeight: "600" }],
        "stat-mono-sm": ["11px", { lineHeight: "14px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "stat-display": ["32px", { lineHeight: "36px", letterSpacing: "-0.03em", fontWeight: "700" }]
      },
      boxShadow: {
        'team-glow': '0 0 20px -3px var(--team-glow, rgba(0, 122, 51, 0.25))',
        'team-card': '0 4px 20px -2px rgba(0, 0, 0, 0.5), 0 0 15px -3px var(--team-glow, rgba(0, 122, 51, 0.15))',
      }
    },
  },
  plugins: [],
}
